<a href="https://colab.research.google.com/github/schoppfe/Deep-Learning-with-PyTorch-2.x/blob/main/03_Numpy_Refresher_Part_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<h1 style="font-size:30px;">Numpy Refresher (Part-3)</h1>

- Element Wise Operations
- Linear Algebra
- Array Statistics


<img src='https://opencv.org/wp-content/uploads/2023/05/c3_w1_NumPy_logo.jpg' width="75%" align='left'><br/>

In [74]:
import numpy as np

def array_info(array):
    print('Array:\n{}'.format(array))
    print('Data type:\t{}'.format(array.dtype))
    print('Array shape:\t{}'.format(array.shape))
    print('Array Dim:\t{}\n'.format(array.ndim))

## 1 Element-Wise Operations


Let's generate two random arrays to demonstrate element-wise operations.

In [75]:
a = np.random.random((4,4))
b = np.random.random((4,4))
array_info(a)
array_info(b)

Array:
[[0.81438936 0.22318356 0.658406   0.34351964]
 [0.42434541 0.25905172 0.00237926 0.73115677]
 [0.47567357 0.03966374 0.74453787 0.10278557]
 [0.13699874 0.18638244 0.91892152 0.32962151]]
Data type:	float64
Array shape:	(4, 4)
Array Dim:	2

Array:
[[0.28878504 0.23250725 0.82291257 0.26864373]
 [0.86341837 0.33735882 0.88755807 0.00164647]
 [0.62039078 0.83213253 0.68995875 0.86441362]
 [0.09257575 0.96184738 0.8535929  0.37396105]]
Data type:	float64
Array shape:	(4, 4)
Array Dim:	2



### 1.1 Element-Wise Scalar Operations

### <font style="color:rgb(50,120,230)">Scalar Addition</font>

In [76]:
a + 5 # Element wise scalar addition.

array([[5.81438936, 5.22318356, 5.658406  , 5.34351964],
       [5.42434541, 5.25905172, 5.00237926, 5.73115677],
       [5.47567357, 5.03966374, 5.74453787, 5.10278557],
       [5.13699874, 5.18638244, 5.91892152, 5.32962151]])

### <font style="color:rgb(50,120,230)">Scalar Subtraction</font>

In [77]:
a - 5 # Element wise scalar subtraction.

array([[-4.18561064, -4.77681644, -4.341594  , -4.65648036],
       [-4.57565459, -4.74094828, -4.99762074, -4.26884323],
       [-4.52432643, -4.96033626, -4.25546213, -4.89721443],
       [-4.86300126, -4.81361756, -4.08107848, -4.67037849]])

### <font style="color:rgb(50,120,230)">Scalar Multiplication</font>

In [78]:
a * 10 # Element wise scalar multiplication.

array([[8.14389355, 2.23183557, 6.58406004, 3.43519636],
       [4.2434541 , 2.59051717, 0.02379255, 7.31156767],
       [4.75673571, 0.39663742, 7.44537866, 1.02785568],
       [1.36998737, 1.86382442, 9.18921518, 3.29621509]])

### <font style="color:rgb(50,120,230)">Scalar Division</font>

In [79]:
a/10 # Element wise scalar division.

array([[0.08143894, 0.02231836, 0.0658406 , 0.03435196],
       [0.04243454, 0.02590517, 0.00023793, 0.07311568],
       [0.04756736, 0.00396637, 0.07445379, 0.01027856],
       [0.01369987, 0.01863824, 0.09189215, 0.03296215]])

### 1.2 Element-Wise Array Operations

### <font style="color:rgb(50,120,230)">Array Addition</font>

In [80]:
a + b # Element wise array/vector addition.

array([[1.1031744 , 0.45569081, 1.48131857, 0.61216337],
       [1.28776378, 0.59641054, 0.88993732, 0.73280323],
       [1.09606435, 0.87179627, 1.43449662, 0.96719918],
       [0.22957448, 1.14822982, 1.77251442, 0.70358256]])

### <font style="color:rgb(50,120,230)">Array Subtraction</font>

In [81]:
a - b # Element wise array/vector subtraction.

array([[ 0.52560431, -0.00932369, -0.16450657,  0.0748759 ],
       [-0.43907296, -0.07830711, -0.88517881,  0.7295103 ],
       [-0.14471721, -0.79246879,  0.05457912, -0.76162805],
       [ 0.04442299, -0.77546494,  0.06532862, -0.04433955]])

### <font style="color:rgb(50,120,230)">Array Multiplication</font>

In [82]:
a * b # Element wise array/vector multiplication.

array([[0.23518347, 0.0518918 , 0.54181058, 0.0922844 ],
       [0.36638762, 0.08739338, 0.00211173, 0.00120383],
       [0.2951035 , 0.03300549, 0.51370042, 0.08884924],
       [0.01268276, 0.17927146, 0.78438488, 0.12326561]])

### <font style="color:rgb(50,120,230)">Array Division</font>

In [83]:
a / b # element wise array/vector division

array([[2.82005378e+00, 9.59899339e-01, 8.00092291e-01, 1.27871823e+00],
       [4.91471370e-01, 7.67881851e-01, 2.68067559e-03, 4.44076308e+02],
       [7.66732170e-01, 4.76651739e-02, 1.07910490e+00, 1.18907854e-01],
       [1.47985559e+00, 1.93775484e-01, 1.07653369e+00, 8.81432719e-01]])

Notice that the dimension of both arrays are equal in the above array element-wise operations. **What if the dimensions are not equal.** Let's check!

In [84]:
print('Array "a":')
array_info(a)
print('Array "c":')
c = np.random.rand(2, 4)
array_info(c)

# Should throw ValueError.
import traceback
try:
    a + c
except Exception:
    traceback.print_exc()

Array "a":
Array:
[[0.81438936 0.22318356 0.658406   0.34351964]
 [0.42434541 0.25905172 0.00237926 0.73115677]
 [0.47567357 0.03966374 0.74453787 0.10278557]
 [0.13699874 0.18638244 0.91892152 0.32962151]]
Data type:	float64
Array shape:	(4, 4)
Array Dim:	2

Array "c":
Array:
[[0.97448971 0.33655222 0.03850298 0.32966448]
 [0.35859052 0.07120541 0.56116738 0.42190106]]
Data type:	float64
Array shape:	(2, 4)
Array Dim:	2



Traceback (most recent call last):
  File "<ipython-input-84-db3a8552b781>", line 10, in <cell line: 9>
    a + c
ValueError: operands could not be broadcast together with shapes (4,4) (2,4) 


<font color='red'>**Oh, got the ValueError!!**</font>

What is this error?

<font color='red'>ValueError</font>: operands could not be broadcast together with shapes `(4,4)` `(2,2)`

### 1.3 Broadcasting

There is a concept of broadcasting in NumPy, which tries to copy rows or columns in the lower-dimensional array to make an equal dimensional array of higher-dimensional array.

<hr style="border:none; height: 4px; background-color:#D3D3D3" />

Documentation: <a href="https://numpy.org/doc/stable/user/basics.broadcasting.html" target=_blank>broadcasting</a>

When operating on two arrays, NumPy compares their shapes element-wise. It starts with the trailing (i.e., rightmost) dimensions and works its way left. Two dimensions are compatible when:

 - They are equal, or
 - One of them is 1

The examples below show how `B` is successfully broadcasted to `A` according to the rules above.

``` python
A      (2d array):  5 x 4
B      (1d array):      1
Result (2d array):  5 x 4

A      (2d array):  5 x 4
B      (1d array):      4
Result (2d array):  5 x 4

A      (3d array):  15 x 3 x 5
B      (3d array):  15 x 1 x 5
Result (3d array):  15 x 3 x 5

A      (3d array):  15 x 3 x 5
B      (2d array):       3 x 5
Result (3d array):  15 x 3 x 5

A      (3d array):  15 x 3 x 5
B      (2d array):       3 x 1
Result (3d array):  15 x 3 x 5
```

<hr style="border:none; height: 4px; background-color:#D3D3D3" />

In [85]:
a = np.array([[1, 2, 3], [4, 5, 6],[7, 8, 9]])
b = np.array([0, 1, 0])

print('Array "a":')
array_info(a)
print('Array "b":')
array_info(b)

print('Array "a+b":')
array_info(a + b)  # b is reshaped such that it can be added to a.

# b = [0,1,0] is broadcasted to     [[0, 1, 0],
#                                    [0, 1, 0],
#                                    [0, 1, 0]]  and added to a.

Array "a":
Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Data type:	int64
Array shape:	(3, 3)
Array Dim:	2

Array "b":
Array:
[0 1 0]
Data type:	int64
Array shape:	(3,)
Array Dim:	1

Array "a+b":
Array:
[[1 3 3]
 [4 6 6]
 [7 9 9]]
Data type:	int64
Array shape:	(3, 3)
Array Dim:	2



## 2 Linear Algebra

In this section, we will take a look at the most commonly used linear algebra operations used in machine learning.

## 2.1 Transpose

<hr style="border:none; height: 4px; background-color:#D3D3D3" />

Either syntax below can be used:

``` python
result = np.transpose(a, axes=None)

result = a.transpose(*axes)

result = a.T
```

Returns a view of the NumPy array `a` with axes transposed.

Documentation: <a href="https://numpy.org/doc/stable/reference/generated/numpy.transpose.html" target=_blank>np.transpose</a>

<hr style="border:none; height: 4px; background-color:#D3D3D3" />


In [86]:
a = np.random.random((2,3))
print('Array "a":')
array_info(a)

print('Transose of "a":')
a_transpose = a.transpose()  # Or a.T
array_info(a_transpose)

Array "a":
Array:
[[0.32995527 0.1083314  0.51513882]
 [0.43994486 0.91787673 0.30879136]]
Data type:	float64
Array shape:	(2, 3)
Array Dim:	2

Transose of "a":
Array:
[[0.32995527 0.43994486]
 [0.1083314  0.91787673]
 [0.51513882 0.30879136]]
Data type:	float64
Array shape:	(3, 2)
Array Dim:	2



### 2.2 Matrix Multiplication
We will discuss two ways of performing matrix multiplication.

- `np.matmul`
- Python `@` operator

### <font style="color:rgb(50,120,230)">Using: `matmul`</font>

<hr style="border:none; height: 4px; background-color:#D3D3D3" />

Using `matmul` is the most common approach for multiplying two matrices using Numpy. Multiplying two matrices requires that the number of columns of the first matrix, `M`, equals the number of rows in the second matrix, `N`, as shown below.

``` python
   M        N      
[p, q] x [q, r] = [p , r]
```
Documentation: <a href="https://numpy.org/doc/stable/reference/generated/numpy.matmul.html" target=_blank>np.matmul</a>

<hr style="border:none; height: 4px; background-color:#D3D3D3" />

In [87]:
a = np.random.random((3, 4))
b = np.random.random((4, 2))

print('Array "a":')
array_info(a)
print('Array "b"')
array_info(b)

# Matrix multiplication of a and b.
%timeit \
c = np.matmul(a,b)

print('matrix multiplication of a and b:')
array_info(c)

print('{} x {} --> {}'.format(a.shape, b.shape, c.shape)) # dim-1 of a and dim-0 of b has to be
                                                          # same for matrix multiplication

Array "a":
Array:
[[0.74270484 0.4022666  0.58624174 0.6882571 ]
 [0.08667922 0.15258479 0.5975048  0.48860495]
 [0.26417607 0.98158362 0.0353965  0.19105891]]
Data type:	float64
Array shape:	(3, 4)
Array Dim:	2

Array "b"
Array:
[[0.89080478 0.29905591]
 [0.50180136 0.01568698]
 [0.93757613 0.28138025]
 [0.06932664 0.59926481]]
Data type:	float64
Array shape:	(4, 2)
Array Dim:	2

1.6 µs ± 389 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
matrix multiplication of a and b:
Array:
[[0.97448971 0.33655222 0.03850298 0.32966448]
 [0.35859052 0.07120541 0.56116738 0.42190106]]
Data type:	float64
Array shape:	(2, 4)
Array Dim:	2

(3, 4) x (4, 2) --> (2, 4)


### <font style="color:rgb(50,120,230)">Using: `@` operator</font>

This method of multiplication was introduced in Python 3.5. <a href="https://www.python.org/dev/peps/pep-0465/" target=_blank>See docs</a>.

In [88]:
a = np.random.random((3, 4))
b = np.random.random((4, 2))

print('Array "a":')
array_info(a)
print('Array "b"')
array_info(b)

# Matrix multiplication of a and b.
%timeit \
c = a@b
array_info(c)

Array "a":
Array:
[[0.05035001 0.14321252 0.63092844 0.84218979]
 [0.9961781  0.01827706 0.21959994 0.08008653]
 [0.07720074 0.80500972 0.35354866 0.35584518]]
Data type:	float64
Array shape:	(3, 4)
Array Dim:	2

Array "b"
Array:
[[0.46343197 0.68196642]
 [0.20405306 0.11142957]
 [0.55121335 0.39729783]
 [0.8142946  0.01824059]]
Data type:	float64
Array shape:	(4, 2)
Array Dim:	2

1.82 µs ± 559 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
Array:
[[0.97448971 0.33655222 0.03850298 0.32966448]
 [0.35859052 0.07120541 0.56116738 0.42190106]]
Data type:	float64
Array shape:	(2, 4)
Array Dim:	2



### 2.3 Matrix Inverse

<hr style="border:none; height: 4px; background-color:#D3D3D3" />

``` python
np.linalg.inv(a)
```

For a square matrix, `a`, compute the (multiplicative) inverse of a matrix.

Documentation: <a href="https://numpy.org/doc/stable/reference/generated/numpy.linalg.inv.html" target=_blank>np.linalg.inv</a>

<hr style="border:none; height: 4px; background-color:#D3D3D3" />


In [89]:
A = np.random.random((3,3))
print('Array "A":')
array_info(A)

A_inverse = np.linalg.inv(A)
print('Inverse of "A" ("A_inverse"):')
array_info(A_inverse)

print('"A x A_inverse = Identity" should be true:')
A_X_A_inverse = np.matmul(A, A_inverse)  # A x A_inverse = I = Identity matrix
array_info(A_X_A_inverse)

Array "A":
Array:
[[0.25183456 0.8510045  0.97038336]
 [0.77502945 0.98702725 0.8931241 ]
 [0.91138044 0.22907147 0.37277938]]
Data type:	float64
Array shape:	(3, 3)
Array Dim:	2

Inverse of "A" ("A_inverse"):
Array:
[[-0.76811447  0.44646741  0.9298119 ]
 [-2.46891063  3.71708884 -2.47876321]
 [ 3.39504155 -3.3756713   1.93251446]]
Data type:	float64
Array shape:	(3, 3)
Array Dim:	2

"A x A_inverse = Identity" should be true:
Array:
[[ 1.00000000e+00  3.30502210e-16  1.87268227e-16]
 [ 1.15023099e-16  1.00000000e+00 -7.57627420e-17]
 [ 7.49899295e-18 -6.06368286e-17  1.00000000e+00]]
Data type:	float64
Array shape:	(3, 3)
Array Dim:	2



### 2.4 Dot Product

The dot product between two euqal length vectors is a scalar defined by the sum of the element-wise product of the two vectors.

<hr style="border:none; height: 4px; background-color:#D3D3D3" />

``` python
np.dot(a, b, out=None)
```


Documentation: <a href="https://numpy.org/doc/stable/reference/generated/numpy.dot.html" target=_blank>np.dot</a>

<hr style="border:none; height: 4px; background-color:#D3D3D3" />


In [90]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

array_info(a)
array_info(b)

dot_prod = np.dot(a, b)
array_info(dot_prod)

Array:
[1 2 3 4]
Data type:	int64
Array shape:	(4,)
Array Dim:	1

Array:
[5 6 7 8]
Data type:	int64
Array shape:	(4,)
Array Dim:	1

Array:
70
Data type:	int64
Array shape:	()
Array Dim:	0



## 3 Array Statistics

### 3.1 Sum

In [91]:
a = np.array([1, 2, 3, 4, 5])

print(a.sum())

15


### 3.2 Sum Along Axis

In [92]:
a = np.array([[1, 2, 3], [4, 5, 6]])
array_info(a)
print('')

print('sum along axis=0: ',a.sum(axis = 0)) # Sum along axis=0 ie: 1+4, 2+5, 3+6
print("")
print('sum along axis=1: ',a.sum(axis = 1)) # Sum along axis=1 ie: 1+2+3, 4+5+6

Array:
[[1 2 3]
 [4 5 6]]
Data type:	int64
Array shape:	(2, 3)
Array Dim:	2


sum along axis=0:  [5 7 9]

sum along axis=1:  [ 6 15]


### 3.3 Minimum and Maximum

In [93]:
a = np.array([-1.1, 2, 5, 100])

print('Minimum = ', a.min())
print('Maximum = ', a.max())

Minimum =  -1.1
Maximum =  100.0


### 3.4 Min and Max along Axis

In [94]:
a = np.array([[-2, 0, 4], [1, 2, 3]])

array_info(a)

print('a =\n',a,'\n')
print('Minimum = ', a.min())
print('Maximum = ', a.max())
print()
print('Minimum along axis 0 = ', a.min(0))
print('Maximum along axis 0 = ', a.max(0))
print()
print('Minimum along axis 1 = ', a.min(1))
print('Maximum along axis 1 = ', a.max(1))

Array:
[[-2  0  4]
 [ 1  2  3]]
Data type:	int64
Array shape:	(2, 3)
Array Dim:	2

a =
 [[-2  0  4]
 [ 1  2  3]] 

Minimum =  -2
Maximum =  4

Minimum along axis 0 =  [-2  0  3]
Maximum along axis 0 =  [1 2 4]

Minimum along axis 1 =  [-2  1]
Maximum along axis 1 =  [4 3]


### 3.5 Mean and Standard Deviation

In [95]:
# Create some data.
data = np.array([1.2, 2.3, 5.0, 3.3, 1.4, 5.6])

print('Mean of the array               = {:8.6f}'.format(data.mean()))
print('Standard deviation of the array = {:8.6f}'.format(data.std()))

Mean of the array               = 3.133333
Standard deviation of the array = 1.684900


### 3.6 Standardizing an Array

Normalize the data array to have `mean=0` and `std=1`.

In [96]:
print('Array              = ', data)
print('Mean               = {:8.6f}'.format(data.mean()))
print('Standard deviation = {:8.6f}'.format(data.std()))
print()

standardized_array = (data - data.mean())/data.std()

print('Standardized Array = ', standardized_array)
print('Mean               = {:8.6f}'.format(standardized_array.mean()))
print('Standard deviation = {:8.6f}'.format(standardized_array.std()))

Array              =  [1.2 2.3 5.  3.3 1.4 5.6]
Mean               = 3.133333
Standard deviation = 1.684900

Standardized Array =  [-1.14744675 -0.49458912  1.10787962  0.09891782 -1.02874536  1.46398379]
Mean               = -0.000000
Standard deviation = 1.000000
